name: bast
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  contact_picker: ^0.0.2
  geolocator: ^2.1.1
  permission_handler: 2.1.2
  google_api_availability: 1.0.4
  http: ^0.12.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # For the Home Page
    - assets/icons/homeIcons/
    - assets/icons/calendar/
    - assets/icons/medRecords/
    - assets/icons/midwife/
  #- images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.otf
        - asset: fonts/Montserrat-Bold.otf
          weight: 700
        - asset: fonts/Montserrat-Italic.otf
          style: italic
  #        weight: 700
    - family: MontserratAlternate
      fonts:
        - asset: fonts/MontserratAlternates-Regular.ttf
        - asset: fonts/MontserratAlternates-Italic.ttf
          style: italic
        - asset: fonts/MontserratAlternates-Bold.ttf
          weight: 700
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
        - asset: fonts/Comfortaa-Light.ttf
          style: italic
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
